image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 8001
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 9009
    onOpen: ignore
  - port: 3306
    onOpen: ignore

tasks:
  - before: bash bash/before-tasks.sh
    init: |
      . bash/third-party/spinner.sh &&
      start_spinner "Initializing MySql..." &&
      gp await-port 3306 &&
      stop_spinner $? &&
      bash bash/init-gitpod.sh &&
      source ~/.bash_profile &&
      url=$(gp url 8000); sed -i'' "s#^APP_URL=http://localhost*#APP_URL=$url\nASSET_URL=$url#g" .env &&
      bash bash/init-optional-scaffolding.sh &&
      bash bash/init-complete.sh
    name: Init
  - openMode: split-left
    command: |
      [ bash bash/helpers.sh is_inited == 0 ] && sudo bash bash/helpers.sh restore_persistant_files
    name: Web Server
  - openMode: split-left
    command: |
      default_server=$(bash bash/utils.sh parse_ini_value starter.ini development default_server); open_preview $default_server
    name: Main Terminal
  - openMode: split-left

vscode:
  extensions:
    - felixfbecker.php-debug@1.14.5:xEr6zDqY853IE2HQtLtXPA==
