image:
  file: .gitpod.Dockerfile

ports:
  - port: 8001
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 9009
    onOpen: ignore
  - port: 3306
    onOpen: ignore

tasks:
  - before: bash bash/before-tasks.sh
    init: |
      bash bash/init-gitpod.sh &&
      bash bash/init-optional-scaffolding.sh &&
      bash bash/init-phpmyadmin.sh &&
      bash bash/init-project.sh &&
      bash bash/init-complete.sh
    name: Startup
  - openMode: split-left
    command: |
      if [ $(bash bash/helpers.sh is_inited) == 1 ]; then \
        gp sync-done gitpod-inited
      fi;
      . bash/third-party/spinner.sh
      UP=$(pgrep mysql | wc -l); \
      if [ "$UP" -ne 1 ]; then \
        start_spinner "Initializing MySql..." &&
        gp await-port 3306 &&
        stop_spinner $?; \
      fi &&
      gp await-port 3306 &&
      __server=$(bash bash/utils.sh parse_ini_value starter.ini development default_server); \
      start_spinner "Starting $__server web server when system is ready..." &&
      gp sync-await gitpod-inited &&
      stop_spinner $? &&
      bash -i bash/helpers.sh start_server
    name: Web Server
  - openMode: split-top
    command: |
      . bash/third-party/spinner.sh &&
      start_spinner "Opening preview when system is ready..."
      gp sync-await gitpod-inited &&
      default_server=$(bash bash/utils.sh parse_ini_value starter.ini development default_server); \
      open_preview $default_server &&
      stop_spinner $?
    name: Main Terminal

vscode:
  extensions:
    - felixfbecker.php-debug@1.14.5:xEr6zDqY853IE2HQtLtXPA==
