image:
  file: .gitpod.Dockerfile

ports:
  - port: 3306
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 8001
    onOpen: ignore
  - port: 8002
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  - port: 9009
    onOpen: ignore

tasks:
  - before: bash .gp/bash/before-tasks.sh
    init: |
      bash .gp/bash/init-gitpod.sh
      bash .gp/bash/init-optional-scaffolding.sh
      bash .gp/bash/init-project.sh
      bash .gp/bash/init-complete.sh
    name: Main Terminal
  - openMode: split-right
    command: |
      if [ $(bash .gp/bash/helpers.sh is_inited) == 1 ]; then \
        gp sync-done gitpod-inited
      fi;
      . .gp/bash/spinner.sh
      UP=$(pgrep mysql | wc -l); \
      if [ "$UP" -ne 1 ]; then \
        start_spinner "Initializing MySql..." &&
        gp await-port 3306 &&
        stop_spinner $?; \
      fi &&
      gp await-port 3306 &&
      __server=$(bash .gp/bash/utils.sh parse_ini_value starter.ini development default_server); \
      start_spinner "Starting $__server web server when system is ready..." &&
      gp sync-await gitpod-inited &&
      stop_spinner $? &&
      bash -i bash/helpers.sh start_server
    name: Web Server
  - openMode: split-right
    command: |
      . .gp/bash/spinner.sh &&
      start_spinner "Opening preview when system is ready..."
      gp sync-await gitpod-inited &&
      stop_spinner 0 &&
      __port=$(bash .gp/bash/helpers.sh get_default_server_port); \
      gp await-port $__port &&
      gp preview $(gp url $__port)
    name: Extra Terminal

vscode:
  extensions:
    - felixfbecker.php-debug@1.14.5:xEr6zDqY853IE2HQtLtXPA==
    - timonwong.shellcheck@0.14.0:3N6vAPyw1UJc4dnF6H7VTQ==
